name: Update Fork
on: [push]
jobs:
  update:
    name: Update Fork
    runs-on: ubuntu-24.04
    if: github.repository == 'scratchaddons-community/suggestions'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{secrets.PAT}}
      - name: Push
        run: |
          git remote add target https://github.com/Jazza-231/suggestions.git
          git push --force target $(git branch --show-current)
