name: Update Fork
on:
    push:
        branches: [main]
jobs:
    update:
        name: Update Fork
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - name: Push
              run: |
                  git remote add target "https://$PAT@github.com/Jazza-231/suggestions.git"
                  git push --force target main
              env:
                  PAT: ${{ secrets.PAT }}
